# Generated by Django 4.2.5 on 2023-10-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
