# Generated by Django 4.1.5 on 2023-11-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_courserating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
