# Generated by Django 4.1.5 on 2023-11-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notify_text',
        ),
    ]
