# Generated by Django 4.1.5 on 2023-11-06 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_password'),
        ('notification', '0002_remove_notification_notify_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
    ]
