# Generated by Django 4.1.5 on 2023-11-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_courserating_course_alter_courserating_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserating',
            name='rating',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='reviews',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
