# Generated by Django 4.1.5 on 2023-11-02 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_delete_courserating'),
        ('student', '0004_delete_studentcourseenrollment'),
        ('rating', '0003_alter_courserating_rating_alter_courserating_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses_rating', to='course.course'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='rating',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='reviews',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student_rating', to='student.student'),
        ),
    ]
